/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyjet;

/**
 *
 * @author admin
 */ import java.sql.*;
import java.util.Date;
import java.text.*;
import javax.swing.table.*;
public class bookaticket extends javax.swing.JFrame {

  Connection conn=null;
Statement s=null;int cost;
    public bookaticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        ifd = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ifrom = new javax.swing.JComboBox<>();
        ito = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ird = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        backimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1045, 730));
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jButton2.setText("PROCEED ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 630, 190, 29);

        res.setFont(new java.awt.Font("Nyala", 3, 14)); // NOI18N
        res.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FROM", "DEPARTURE DATE & TIME", "TO", "ARRIVAL DATE & TIME", "FLIGHT CODE", "PRICE($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        res.setOpaque(false);
        jScrollPane1.setViewportView(res);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 400, 1030, 90);

        jButton1.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 320, 170, 29);

        ifd.setFont(new java.awt.Font("Nyala", 3, 14)); // NOI18N
        ifd.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1502860020000L), new java.util.Date(1502860020000L), new java.util.Date(1623301620000L), java.util.Calendar.DAY_OF_MONTH));
        getContentPane().add(ifd);
        ifd.setBounds(200, 250, 70, 20);

        jLabel4.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel4.setText("DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 250, 50, 20);

        jLabel3.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel3.setText("TO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 170, 34, 30);

        jLabel2.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel2.setText("FROM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 170, 60, 20);

        jLabel1.setFont(new java.awt.Font("Nyala", 3, 36)); // NOI18N
        jLabel1.setText("BOOK A TICKET");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 80, 270, 39);

        jLabel5.setFont(new java.awt.Font("Nyala", 3, 70)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("SKYJET");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 0, 250, 70);

        ifrom.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        ifrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEW YORK(NYC)", "TAKAKA,NEW ZEALAND(KTF)", "NEWARK(EWR)", "NEW DELHI(DEL)", "KUALA LUMPUR(KUL)", "BANGKOK,THAILAND(BKK)", "BENGALURU(BLR)", "KOLKATA(CCU)", "CHENNAI(MAA)", "DUBAI,UAE(DXB)", "LONDON(LHR)", "PARIS(CDG)", "EDMONTON,CANADA(YEG)", "MUMBAI(BOM)", " " }));
        getContentPane().add(ifrom);
        ifrom.setBounds(80, 170, 270, 25);

        ito.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        ito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEW YORK(NYC)", "TAKAKA,NEW ZEALAND(KTF)", "NEWARK(EWR)", "NEW DELHI(DEL)", "KUALA LUMPUR(KUL)", "BANGKOK,THAILAND(BKK)", "BENGALURU(BLR)", "KOLKATA(CCU)", "CHENNAI(MAA)", "DUBAI,UAE(DXB)", "LONDON(LHR)", "PARIS(CDG)", "EDMONTON,CANADA(YEG)", "MUMBAI(BOM)" }));
        getContentPane().add(ito);
        ito.setBounds(420, 170, 270, 25);

        jLabel7.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel7.setText("RETURN DATE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 250, 120, 20);

        ird.setFont(new java.awt.Font("Nyala", 3, 14)); // NOI18N
        ird.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(ird);
        ird.setBounds(460, 250, 70, 22);

        jLabel9.setFont(new java.awt.Font("Nyala", 3, 12)); // NOI18N
        jLabel9.setText("MM/DD/YY");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 280, 70, 13);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyjet/MAIN Logo.PNG"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 200, 108);

        backimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyjet/I5.jpg"))); // NOI18N
        getContentPane().add(backimg);
        backimg.setBounds(0, 0, 1030, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int p=res.getSelectedRow();


try
{
    Class.forName("java.sql.Driver");
  conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/skyjet","root","server");
  s=conn.createStatement();
  login l=new login();
  int pnr=00;
 if(l.data().isEmpty()!=true)
 {
        pnr=l.ipnr();
 }
else
 {
 l.setVisible(true);
 }
 int r=res.getSelectedRow();
 String q="insert into tickets values("+pnr+",'"+res.getValueAt(r,4)+"',"+"'"+res.getValueAt(r,0)+"',"+res.getValueAt(r,2)+"');";
 
 s.executeUpdate(q);
 cost=(int)res.getValueAt(r,6);
 
 paymentdetails pm=new paymentdetails();
 pm.setVisible(true);
 
  
  
  
 
}catch(Exception e)
{
    System.out.println(e.getMessage());
    
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/skyjet","root","server");
            s=conn.createStatement();
            String from=(String)ifrom.getSelectedItem();
            String to=(String)ito.getSelectedItem();
            Date fd=new Date();
            Date rd=new Date();
            fd=(Date)ifd.getValue();
            rd=(Date)ird.getValue();
            SimpleDateFormat ff=new SimpleDateFormat("yyyy/MM/dd");
            String sfa=ff.format(fd).toString();
            String srd=ff.format(rd).toString();
            ResultSet rs=s.executeQuery("select * from dflights where from_='"+from+"' and to_='"+to+"' and date(departure) ='"+fd+"' and date(arrival)='"+rd+"';");
            DefaultTableModel dtm=(DefaultTableModel)res.getModel();

            while(rs.next())
            {Object s[]={from,rs.getDate("departure"),to,rs.getDate("arrival"),rs.getInt("flightcode"),rs.getInt("price")};
                dtm.addRow(s);
                res.setModel(dtm);
            }

        }catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
public double price()
{
    return cost;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookaticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookaticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookaticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookaticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookaticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backimg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSpinner ifd;
    private javax.swing.JComboBox<String> ifrom;
    private javax.swing.JSpinner ird;
    private javax.swing.JComboBox<String> ito;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable res;
    // End of variables declaration//GEN-END:variables

    
}
