/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyjet;

import java.sql.Connection;
import java.sql.*;

/**
 *
 * @author admin
 */
public class changebooking extends javax.swing.JFrame {

    /**
     * Creates new form changebooking
     */
    public changebooking() {
        initComponents();
    }
Connection conn=null;
Statement s=null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(776, 420));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Nyala", 3, 70)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("SKYJET");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 0, 250, 70);

        jLabel1.setFont(new java.awt.Font("Nyala", 3, 36)); // NOI18N
        jLabel1.setText("CHANGE BOOKING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 90, 320, 39);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyjet/MAIN Logo.PNG"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 200, 108);

        jLabel2.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel2.setText("FLIGHT PNR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 190, 100, 20);

        pnr.setFont(new java.awt.Font("Nyala", 3, 14)); // NOI18N
        pnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnrActionPerformed(evt);
            }
        });
        getContentPane().add(pnr);
        pnr.setBounds(170, 190, 80, 22);

        jLabel3.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel3.setText("FLYER NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 150, 110, 20);

        name.setFont(new java.awt.Font("Nyala", 3, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(170, 150, 170, 20);

        jButton2.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jButton2.setText("CANCEL BOOKING");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 250, 200, 29);

        jLabel4.setFont(new java.awt.Font("Nyala", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("$100 WILL BE CHARGED AS CANCELLATION FEE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 370, 280, 14);

        jLabel6.setFont(new java.awt.Font("Nyala", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("**");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 380, 20, 13);

        backimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyjet/changeb.jpg"))); // NOI18N
        getContentPane().add(backimg);
        backimg.setBounds(0, 0, 790, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnrActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try
      {
          Class.forName("java.sql.Driver");
            conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/skyjet","root","server");
            s=conn.createStatement();
            String s="delete from tickets where name='"+name.getText()+"'"+" and pnr="+pnr.getText()+";";
      }catch(Exception e)
      {
          
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changebooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backimg;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pnr;
    // End of variables declaration//GEN-END:variables
}
