/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyjet;

/**
 *
 * @author admin
 */import java.sql.*;
public class createid extends javax.swing.JFrame {

    /**
     * Creates new form createid
     */
    public createid() {
        initComponents();
    }
Connection conn=null;
Statement s=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        passre = new javax.swing.JPasswordField();
        backimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 581));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nyala", 3, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("SKYJET");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 0, 230, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyjet/MAIN Logo.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(663, 0, 200, 100);

        jLabel3.setFont(new java.awt.Font("Nyala", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("CREATE I.D");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 200, 39);

        jLabel4.setFont(new java.awt.Font("Nyala", 3, 24)); // NOI18N
        jLabel4.setText("NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 290, 240, 25);

        create.setBackground(new java.awt.Color(255, 0, 0));
        create.setFont(new java.awt.Font("Nyala", 3, 24)); // NOI18N
        create.setText("CREATE I.D");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        getContentPane().add(create);
        create.setBounds(300, 530, 220, 35);
        getContentPane().add(name);
        name.setBounds(270, 290, 250, 25);

        jLabel9.setFont(new java.awt.Font("Nyala", 3, 24)); // NOI18N
        jLabel9.setText("CREATE PASSWORD");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 430, 220, 26);

        jLabel10.setFont(new java.awt.Font("Nyala", 3, 24)); // NOI18N
        jLabel10.setText("RE-TYPE PASSWORD");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 470, 220, 26);
        getContentPane().add(pass);
        pass.setBounds(270, 430, 230, 25);
        getContentPane().add(passre);
        passre.setBounds(270, 470, 230, 25);

        backimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyjet/create id.jpg"))); // NOI18N
        getContentPane().add(backimg);
        backimg.setBounds(0, 0, 860, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
try
{
  Class.forName("java.sql.Driver");
  conn=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/skyjet","root","server");
  s=conn.createStatement();
  String n=name.getText();
  String passs=new String(pass.getPassword());
 
 
  int fy;
  ResultSet rs=s.executeQuery("select pnr from users; ");
  rs.last();
  fy=rs.getInt(1)+1;
  s.executeUpdate("insert into users values('"+n+"',"+passs+",'"+fy+"',"+fy+");");
  
  
  
}catch(Exception e)
{
    System.out.println(e.getMessage());
}
        
    }//GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backimg;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField passre;
    // End of variables declaration//GEN-END:variables
}
