/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyjet;

import java.sql.Connection;
import java.sql.*;


/**
 *
 * @author admin
 */
public class paymentdetails extends javax.swing.JFrame {

    /**
     * Creates new form paymentdetails
     */
    public paymentdetails() {
        initComponents();
    }
Connection conn=null;
Statement s=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        debitcard = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        icvv = new javax.swing.JTextField();
        icd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        online = new javax.swing.JButton();
        card = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        accno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        seccode = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(829, 540));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        debitcard.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel13.setText("CVV");

        icvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icvvActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel1.setText("Card No.");

        javax.swing.GroupLayout debitcardLayout = new javax.swing.GroupLayout(debitcard);
        debitcard.setLayout(debitcardLayout);
        debitcardLayout.setHorizontalGroup(
            debitcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debitcardLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(debitcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(debitcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icd, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icvv, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        debitcardLayout.setVerticalGroup(
            debitcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debitcardLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(debitcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(debitcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(icd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(debitcard);
        debitcard.setBounds(470, 250, 330, 90);

        jButton3.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jButton3.setText("PAY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 400, 130, 23);

        online.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        online.setText("ONLINE BOOKING");
        online.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineActionPerformed(evt);
            }
        });
        getContentPane().add(online);
        online.setBounds(0, 180, 250, 29);

        card.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        card.setText("CREDIT CARD/DEBIT CARD");
        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });
        getContentPane().add(card);
        card.setBounds(0, 140, 250, 29);

        jLabel4.setFont(new java.awt.Font("Nyala", 3, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("SKYJET");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 0, 250, 70);

        jLabel5.setFont(new java.awt.Font("Nyala", 3, 48)); // NOI18N
        jLabel5.setText("PAYMENT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 80, 220, 51);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyjet/MAIN Logo.PNG"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 200, 110);

        jLabel11.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel11.setText("        ACC NO.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 290, 120, 20);

        accno.setFont(new java.awt.Font("Nyala", 3, 14)); // NOI18N
        accno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnoActionPerformed(evt);
            }
        });
        getContentPane().add(accno);
        accno.setBounds(130, 290, 130, 20);

        jLabel12.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel12.setText("SECRET CODE");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 330, 120, 20);

        seccode.setText(" ");
        seccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seccodeActionPerformed(evt);
            }
        });
        getContentPane().add(seccode);
        seccode.setBounds(130, 330, 130, 20);

        background.setFont(new java.awt.Font("Nyala", 3, 48)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyjet/I4.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(-30, 0, 860, 540);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 370, 170, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       
       
    }//GEN-LAST:event_formKeyPressed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void icvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icvvActionPerformed

    private void accnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnoActionPerformed

    private void seccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seccodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seccodeActionPerformed

    private void onlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineActionPerformed
      accno.setVisible(true);
      seccode.setVisible(true);
      jLabel12.setVisible(true);
      jLabel11.setVisible(true);
      debitcard.setVisible(false);
              
    }//GEN-LAST:event_onlineActionPerformed

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
          accno.setVisible(false);
      seccode.setVisible(false);
      jLabel12.setVisible(false);
      jLabel11.setVisible(false);
      debitcard.setVisible(true);
    }//GEN-LAST:event_cardActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try
       {
         Class.forName("java.sql.Driver");
  conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/skyjet","root","server");
  s=conn.createStatement(); 
if(accno.isVisible()==true)
{
String a=accno.getText();
String pass=seccode.getText();login p=new login();

String o="insert into bank values ('"+a+"','"+pass+"'"+","+p.ipnr()+",);";
s.executeUpdate(o);
    
}
if(debitcard.isVisible()==true)
{
String a=icd.getText();
String pass=icvv.getText();login p=new login();

String o="insert into bank values ('"+a+"','"+pass+"'"+","+p.ipnr()+",);";
s.executeUpdate(o);
    
}

home1 a=new home1();
a.setVisible(true);



  
       }catch(Exception e)
       {
           
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accno;
    private javax.swing.JLabel background;
    private javax.swing.JButton card;
    private javax.swing.JPanel debitcard;
    private javax.swing.JTextField icd;
    private javax.swing.JTextField icvv;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton online;
    private javax.swing.JTextField seccode;
    // End of variables declaration//GEN-END:variables
}
