/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skyjet;

/**
 *
 * @author admin
 */ import java.sql.*;

public class skymiles extends javax.swing.JFrame {
Connection conn=null;
Statement s=null;
    
    public skymiles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        miles = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        backimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(808, 454));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Nyala", 3, 70)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("SKYJET");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 10, 230, 70);

        jLabel1.setFont(new java.awt.Font("Nyala", 3, 36)); // NOI18N
        jLabel1.setText("SKYMILES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 80, 160, 39);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyjet/MAIN Logo.PNG"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 200, 108);

        jLabel2.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel2.setText("FLYER NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 170, 120, 30);

        name.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        getContentPane().add(name);
        name.setBounds(210, 170, 210, 30);

        jLabel3.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel3.setText("SKYMILES");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 240, 90, 30);

        miles.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        getContentPane().add(miles);
        miles.setBounds(210, 240, 150, 30);

        jButton1.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jButton1.setText("HOME PAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 380, 150, 40);

        backimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyjet/skymiles.jpg"))); // NOI18N
        getContentPane().add(backimg);
        backimg.setBounds(0, 0, 808, 454);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
home1 p=new home1();
p.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try
{
  Class.forName("java.sql.Driver");
  conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/skyjet","root","server");
  s=conn.createStatement();
  login l=new login();
   ResultSet rs=null;
  if(l.data().isEmpty()!=true)
  {
       rs=s.executeQuery("select skymiles from users where name='"+l.data()+"';");
  }
  else
  {
       l.setVisible(true);
       
  }
  int sk=rs.getInt("skymiles");
  miles.setText(""+sk);
  name.setText(""+l.data());
  
  
}catch(Exception e)
{
    System.out.println(e.getMessage());
}
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(skymiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(skymiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(skymiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(skymiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new skymiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backimg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel miles;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
